name: az-test
favicon: null
layout_spectrum: 0.941
typography_spectrum: 0.50722
title: Andrew Zhang Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f3ee'
    - '#18292a'
    - '#7d5d3a'
    - '#b4bbbf'
    - '#6d8897'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
